In [ ]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.8 MB 11.4 MB/s eta 0:00:01
   ------------- -------------------------- 4.5/12.8 MB 11.4 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.8 MB 10.0 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.8 MB 8.6 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.8 MB 6.8 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/12.8 MB 5.8 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.8 MB 5.5 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.8 MB 4.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.8 MB 4.5 MB/s eta 0:00:01
   --------------------------- ------------ 8.9/12.8 MB 4.3 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.8 MB 4.1 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.8 MB 4.0 MB/s eta 0:00:01
  


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
#using tuple
#same data type
a=np.array((1,2,3))
print(a)

[1 2 3]


In [5]:
#different datatype
a=np.array((1,2,3,"hello"))
print(a)

['1' '2' '3' 'hello']


In [6]:
#using list
#same datatype
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
#different datatype
a=np.array([1,2,2,"hello",12,3.5])
print(a)

['1' '2' '2' 'hello' '12' '3.5']


In [8]:
#1d array
#using list
a=np.array([2,3,4,5,6])
print(a)

[2 3 4 5 6]


In [9]:
a=np.array([1,2,3,"hello","hi",2.3])
print(a)

['1' '2' '3' 'hello' 'hi' '2.3']


In [10]:
#using tuple
a=np.array((1,2,3,4))
print(a)

[1 2 3 4]


In [11]:
a=np.array((1,2,3,"hello"))
print(a)

['1' '2' '3' 'hello']


In [14]:
#2d array
#using list
a=np.array([[2,3,4,5,6]])
print(a)

[[2 3 4 5 6]]


In [16]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
#using tuple
a=np.array([(1,2,3,4,5,6)])
print(a)

[[1 2 3 4 5 6]]


In [21]:
a=np.array([(1,2,3),
            (4,5,6),
            (7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#d3 array
#using list
a=np.array([[[2,3,4,5,4,2,8,]]])
print(a)

[[[2 3 4 5 4 2 8]]]


In [3]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]])
print(a)

[[[2 3]
  [6 8]
  [4 2]]]


In [4]:
a=np.array([[[2,3],[6,8],[4,2]]])
print(a)

[[[2 3]
  [6 8]
  [4 2]]]


In [5]:
#using tuple
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)

[[[2 3 4 5 2 4 5]]]


In [6]:
a=np.array([[(2,3,4),
             (6,5,7),
             (4,1,2)]])
print(a)

[[[2 3 4]
  [6 5 7]
  [4 1 2]]]


In [7]:
#2d array with 4*3 order
a=np.array([[1,2,3],
            [4,2,1],
            [8,4,2]])
print(a)

[[1 2 3]
 [4 2 1]
 [8 4 2]]


In [8]:
#3d array with 3*3 order
a=np.array([[[2,5,1],
             [5,2,8],
             [2,5,7]]])
print(a)

[[[2 5 1]
  [5 2 8]
  [2 5 7]]]


#ndim :returns the number of dimension of the array

In [9]:
a=np.array([[[2,5,1],
             [5,2,8],
             [2,5,7]]])
print(a)
print(a.ndim)

[[[2 5 1]
  [5 2 8]
  [2 5 7]]]
3


In [10]:
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)
print(a.ndim)

[[[2 3 4 5 2 4 5]]]
3


In [11]:
a=np.array([(1,2,3,4,5,6)])
print(a)
print(a.ndim)

[[1 2 3 4 5 6]]
2


#size :returns the number of elements in an array

In [12]:
a=np.array([[[2,5,1],
             [5,2,8],
             [2,5,7]]])
print(a)
print(a.size)

[[[2 5 1]
  [5 2 8]
  [2 5 7]]]
9


In [13]:
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)
print(a.size)

[[[2 3 4 5 2 4 5]]]
7


#shape : returns the size of the array in each dimension

In [ ]:
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)
print(a.shape)

[[[2 5 1]
  [5 2 8]
  [2 5 7]]]
(1, 3, 3)


In [15]:
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)
print(a.shape)

[[[2 3 4 5 2 4 5]]]
(1, 1, 7)


In [16]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]])
print(a)
print(a.shape)

[[[2 3]
  [6 8]
  [4 2]]]
(1, 3, 2)


type : returns the library and data stucture 

In [17]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]])
print(a)
print(type(a))

[[[2 3]
  [6 8]
  [4 2]]]
<class 'numpy.ndarray'>


In [18]:
a=np.array([[(2,3,4,5,2,4,5)]])
print(a)
print(type(a))

[[[2 3 4 5 2 4 5]]]
<class 'numpy.ndarray'>


In [19]:
a=np.array([[[2,5,1],
             [5,2,8],
             [2,5,7]]])
print(a)
print(type(a))

[[[2 5 1]
  [5 2 8]
  [2 5 7]]]
<class 'numpy.ndarray'>


#dtype :change data type of element in an array

In [20]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]],dtype=float)
print(a)

[[[2. 3.]
  [6. 8.]
  [4. 2.]]]


In [21]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]],dtype=int)
print(a)

[[[2 3]
  [6 8]
  [4 2]]]


#itemsize :return the size of each elements in an array(in bytes)

In [22]:
a=np.array([[[2,3],
             [6,8],
             [4,2]]])
print(a.itemsize)

8


In [23]:
a=np.array([[[2,5,1],
             [5,2,8],
             [2,5,7]]])
print(a.itemsize)

8


#nbytes :returns the total number of bytes required to store the array

In [24]:
a=np.array([1,5,4,8,2,2,8,1,3],dtype=int)
print(a.nbytes)

72


special functions

In [ ]:
# np.zeros()
# 1d
a=np.zeros((5,))
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
# 2d
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 3d
a=np.zeros((1,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
a=np.zeros((3,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# np.ones()
# 1d
a=np.ones((5,))
print(a)

[1. 1. 1. 1. 1.]


In [3]:
# 2d
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# 3d
a=np.ones((1,2,3))
print(a)

a=np.ones([2,2,3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
# np.full()
# 1d
a=np.full((5),7)
print(a)

[7 7 7 7 7]


In [7]:
a=np.full((5),"hi")
print(a)

['hi' 'hi' 'hi' 'hi' 'hi']


In [8]:
# 2d
a=np.full((3,3),7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [9]:
# 3d
a=np.full((1,2,3),7)
print(a)

[[[7 7 7]
  [7 7 7]]]


In [10]:
# np.arange()
# 1d
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [5]:
a=np.arange(1,7,2)
print(a)

[1 3 5]


In [3]:
# 2d
a=np.arange(5)
b=np.reshape(a,(1,5))
print(b)

[[0 1 2 3 4]]


In [4]:
# 3d
a=np.arange(5)
b=np.reshape(a,(1,1,5))
print(b)

[[[0 1 2 3 4]]]


In [19]:
a=np.arange(24)
b=np.reshape(a,(2,3,4))
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.arange(50)
b=np.reshape(a,(5,2,5))
print(b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]]


In [15]:
# np.linspace()
a=np.linspace(1,10)
print(a)
print(a.size)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
50


In [16]:
a=np.linspace(1,20)
print(a)
print(a.size)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
50


In [10]:
# np.eye()
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
a=np.eye(4,k=1)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [19]:
a=np.eye(4,k=-1)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
a=np.eye(4,k=2)
print(a)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# np.identity()
a=np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# np.diag()
a=np.diag([7,4,5,6])
print(a)

[[7 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [7]:
a=np.diag([7,4,5,6],k=1)
print(a)

[[0 7 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]
 [0 0 0 0 0]]


In [26]:
a=np.diag([7,4,5,6],k=-1)
print(a)

[[0 0 0 0 0]
 [7 0 0 0 0]
 [0 4 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]]


creates arrays using random number generation

In [27]:
# np.random.rand()
# 1d
a=np.random.rand(5)
print(a)

[0.31228488 0.39261294 0.26425856 0.28995236 0.44676893]


In [28]:
# 2d
a=np.random.rand(3,4)
print(a)

[[0.20424256 0.11316139 0.22246163 0.99697819]
 [0.39547803 0.06146922 0.64475154 0.11027921]
 [0.63815141 0.15068682 0.63202446 0.5519227 ]]


In [29]:
# 3d
a=np.random.rand(2,3,4)
print(a)

[[[0.2307869  0.55356659 0.43305929 0.63108454]
  [0.74723505 0.28708634 0.21339895 0.08520494]
  [0.42138645 0.06068234 0.52218543 0.43205491]]

 [[0.44588519 0.30108085 0.07380347 0.60507883]
  [0.98246895 0.83656007 0.39122453 0.25274839]
  [0.88054972 0.69264938 0.97906619 0.79374303]]]


In [31]:
# np.random.randn()
a=np.random.randn(5)
print(a)

[-0.67433996 -0.37409529 -0.05630809  1.05498705  0.69776704]


In [32]:
a=np.random.randn(3,4)
print(a)

[[-1.20383956  1.43996189 -0.63174108  0.13284704]
 [-1.73715003  0.40468886  1.75699147  1.27406153]
 [ 0.705562    0.42709725 -0.63385588  2.17535255]]


In [33]:
a=np.random.randn(2,3,4)
print(a)

[[[-1.49963377 -0.85577277 -2.76305324  0.24463588]
  [-0.29103094  1.13071005 -0.81358991  1.65148744]
  [-0.39604318  2.32983617 -1.00068463  0.02516703]]

 [[ 0.07729177 -0.65068328  0.25099993  0.61204063]
  [-0.91140004  0.59680846 -1.82415076 -1.25927011]
  [ 0.8702191   0.98990394 -1.10594686  0.79010298]]]


In [36]:
# np.random.randint()
a=np.random.randint(10)
print(a)

9


In [37]:
a=np.random.randint(5,10)
print(a)

7


In [12]:
a=np.random.randint(5,10,3)
print(a)

[8 8 7]


In [39]:
# 2d
a=np.random.randint(1,10,(3,4))
print(a)

[[5 3 7 5]
 [7 2 4 7]
 [4 9 8 3]]


In [ ]:
a=np.random.randint(1,10,size=(3,4))
print(a)

[[[9 4 8 5]
  [3 5 2 3]
  [9 9 7 4]]

 [[7 6 5 8]
  [1 3 3 9]
  [9 3 4 7]]]


In [ ]:
# empty
a=np.empty((3,5))
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  6.81019663e-310]]


In [43]:
# create a data type
a=np.empty((3,3),dtype=int)
print(a)

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]


In [2]:
a=np.array([1,2,3],dtype=str)
print(a)

['1' '2' '3']


In [3]:
# typecasting
# ndarray.array(dtype)
a=np.array([1,2,3])
print(a.dtype)

int64


In [4]:
b=a.astype("float64")
print(b)
print(b.dtype)

[1. 2. 3.]
float64


basic operations

<!-- Basic operations and mathematical functions -->

1) Arithematic operations 

In [ ]:

a=np.array([[1,2,3],[5,8,2],[8,5,9]])
b=np.array([[5,8,1],[8,2,5],[2,6,9]])
print(a)
print(b)

[[1 2 3]
 [5 8 2]
 [8 5 9]]
[[5 8 1]
 [8 2 5]
 [2 6 9]]


In [10]:
# addition:np.add()
c=np.add(a,b)
print(c)

[[ 6 10  4]
 [13 10  7]
 [10 11 18]]


In [11]:
# with a scalar value
print(a)
c=np.add(a,2)
print(c)

[[1 2 3]
 [5 8 2]
 [8 5 9]]
[[ 3  4  5]
 [ 7 10  4]
 [10  7 11]]


In [2]:
# substraction
a=np.array([[1,2,3],[5,8,2],[8,5,9]])
b=np.array([[5,8,1],[8,2,5],[2,6,9]])
print(a)
# print(b)
c=np.subtract(a,b)
print(c)

[[1 2 3]
 [5 8 2]
 [8 5 9]]
[[-4 -6  2]
 [-3  6 -3]
 [ 6 -1  0]]


In [22]:
c=np.subtract(a,2)
print(c)

[[-1  0  1]
 [ 3  6  0]
 [ 6  3  7]]


In [23]:
# multiplication
c=np.multiply(a,b)
print(c)

[[ 5 16  3]
 [40 16 10]
 [16 30 81]]


In [24]:
c=np.multiply(a,2)
print(c)

[[ 2  4  6]
 [10 16  4]
 [16 10 18]]


In [26]:
# division
c=np.divide(a,b)
print(c)

[[0.2        0.25       3.        ]
 [0.625      4.         0.4       ]
 [4.         0.83333333 1.        ]]


In [28]:
# floor_division
c=np.floor_divide(a,b)
print(c)

[[0 0 3]
 [0 4 0]
 [4 0 1]]


In [30]:
# modular
c=np.mod(a,b)
print(c)

[[1 2 0]
 [5 0 2]
 [0 5 0]]


In [ ]:
# power
c=np.power(a,b)
print(c)

[[   1  128]
 [3125 4096]]


In [4]:
# matrix multiplication
# 1d
a=np.array([1,2,3])
b=np.array([5,6,2])
e=np.multiply(a,b)
c=np.dot(a,b)
print(e)
print(c)

[ 5 12  6]
23


In [ ]:
# 2d
a=np.array([[1,2],
            [5,4]])
b=np.array([[3,7],
            [5,6]])
e=np.multiply(a,b)
c=np.dot(a,b)
print(e)
print(c)

[[ 3 14]
 [25 24]]
[[13 19]
 [35 59]]


comparison 

<!-- comarison operators -->
<!-- ==,!=,>,<,>=,<= -->

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,1,2])
print(a==b)

[False False False False False]


In [38]:
a=np.array([[1,2,3],
            [5,8,6],
            [7,2,6]])
b=np.array([[4,5,6],
            [5,2,8],
            [8,2,5]])
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

[[False False False]
 [ True False False]
 [False  True False]]
[[ True  True  True]
 [False  True  True]
 [ True False  True]]
[[False False False]
 [False  True False]
 [False False  True]]
[[ True  True  True]
 [False False  True]
 [ True False False]]
[[False False False]
 [ True  True False]
 [False  True  True]]
[[ True  True  True]
 [ True False  True]
 [ True  True False]]


In [39]:
# with a scalar value 
a=np.array([1,2,3,4,5])
b=5
print(a==b)
print(a!=b)

[False False False False  True]
[ True  True  True  True False]


In [40]:
# qstn1
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [41]:
# qstn2
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [42]:
# qstn3
a=np.array((10,20,30))
print(a)

[10 20 30]


In [47]:
# qstn4
a=np.zeros(10,)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# qstn4
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


unary operations

<!-- unary operations -->

In [3]:
# absolute value
a=np.array([-1,+2,3,-2,-4,-5])
b=np.abs(a)
print(b)

[1 2 3 2 4 5]


In [4]:
# square
a=np.array([[6,8,7,4],[5,7,1,5],[7,1,5,8]])
b=np.square(a)
print(b)

[[36 64 49 16]
 [25 49  1 25]
 [49  1 25 64]]


In [7]:
# square root
a=np.array([[64,36,16],[56,12,8]])
b=np.sqrt(a)
print(b)

[[8.         6.         4.        ]
 [7.48331477 3.46410162 2.82842712]]


agrigate functions

In [ ]:
# 1) sum
# 1d
a=np.array([1,2,3])
b=np.sum(a)
print(b)

6


In [10]:
# 2d
a=np.array([[1,2,3],
           [5,4,6]])
b=np.sum(a)
print(b)

21


In [11]:
# 2d--column wise sum
a=np.array([[1,2,3],
           [5,4,6]])
b=np.sum(a,axis=0)
print(b)

[6 6 9]


In [12]:
# 2d--row wise sum
a=np.array([[1,2,3],
           [5,4,6]])
b=np.sum(a,axis=1)
print(b)

[ 6 15]


In [13]:
# 3d --column wise sum==>axis1
a-np.array([[[5,2,3],
             [5,4,6]]])
b=np.sum(a,axis=1)
print(b)

[ 6 15]


In [3]:
# 3d --row wise sum==>axis2
a=np.array([[[5,2,3],
             [5,4,6]]])
b=np.sum(a,axis=2)
print(b)

[[10 15]]


In [5]:
# 2) prodct
# 1d
a=np.array([1,2,3])
b=np.prod(a)
print(b)

6


In [7]:
# 2d
a=np.array([[1,2,3],
            [5,4,6]])
b=np.prod(a)
print(b)

720


In [8]:
# 2d--column wise prod
a=np.array([[1,2,3],
            [5,4,6]])
b=np.prod(a,axis=0)
print(b)

[ 5  8 18]


In [9]:
# 2d--row wise prod
a=np.array([[1,2,3],
            [5,4,6]])
b=np.prod(a,axis=1)
print(b)


[  6 120]


In [11]:
# 3d--column wise prod==>axis=1
a=np.array([[[5,2,3],
             [5,4,6]]])
b=np.prod(a,axis=1)
print(b)

[[25  8 18]]


In [ ]:
# 3d--row wise prod==>axis=2
a=np.array([[[5,2,3],
             [5,4,6]]])
b=np.prod(a,axis=2)
print(b)

In [12]:
# 3) minimum
# 1d
a=np.array([1,34,23,56])
b=np.min(a)
print(b)

1


In [13]:
# 2d
a=np.array([[21,42,3],
            [75,4,16]])
b=np.min(a)
print(b)

3


In [14]:
c=np.min(a,axis=0)
print(c)

[21  4  3]


In [16]:
# 3d
a=np.array([[[21,42,3],
            [75,4,16]]])
b=np.min(a)
print(b)

3


In [ ]:
c=np.min(a,axis=0)
print(c)

[[[21 42  3]
  [75  4 16]]]
[[21 42  3]
 [75  4 16]]


In [21]:
# 4)maximum
# 1d
a=np.array([12,34,56,33])
b=np.max(a)
print(b)

56


In [22]:
# 2d
a=np.array([[21,42,3],
            [75,4,16]])
b=np.max(a)
print(b)

75


In [27]:
c=np.max(a,axis=0)
print(c)

[75 42 16]


In [28]:
# 3d
a=np.array([[[21,42,3],
            [75,4,16]]])
b=np.max(a)
print(b)

75


In [29]:
# 5) mean
# 1d
a=np.array([1,2,3])
b=np.mean(a)
print(b)

2.0


In [ ]:
# 2d
a=np.array([[21,44,3],
            [75,4,16]])
b=np.mean(a)
print(b)
c=np.mean(a,axis=0) #column wise
print(c)
d=np.mean(a,axis=1) #row wise
print(d)

27.166666666666668
[48.  24.   9.5]
[22.66666667 31.66666667]


In [34]:
# 3d
a=np.array([[[21,44,3],
            [75,4,16]]])
b=np.mean(a)
print(b)
c=np.mean(a,axis=1) #column wise
print(c)
d=np.mean(a,axis=2) #row wise
print(d)

27.166666666666668
[[48.  24.   9.5]]
[[22.66666667 31.66666667]]


rounding function

In [ ]:
#1) np.round
a=np.array([[6.5,7.5,1.6],[5.6,2.2,8.5]])
b=np.round(a)
print(b)

[[6. 8. 2.]
 [6. 2. 8.]]


In [3]:
# 2)np.floor
a=np.array([[6.5,7.5,1.6],[5.6,2.2,8.5]])
b=np.floor(a)
print(b)

[[6. 7. 1.]
 [5. 2. 8.]]


In [4]:
# 3) np.ceil
a=np.array([[6.5,7.5,1.6],[5.6,2.2,8.5]])
b=np.ceil(a)
print(b)

[[7. 8. 2.]
 [6. 3. 9.]]


In [2]:
# 4)trunc()
a=np.array([[6.4,3.6,1.6],[5.6,1.2,8.5]])
b=np.trunc(a)
print(b)

[[6. 3. 1.]
 [5. 1. 8.]]


indexing

In [15]:
# 1d
a=np.array([1,2,3,4,5])
print(a[0])

1


In [5]:
a=np.array([1,2,3,4,5])
print(a[0:2])

[1 2]


In [7]:
a=np.array([1,2,3,4,5,6])
print(a[0:5:2])

[1 3 5]


In [8]:
a=np.arange(30,61)
print(a)
print(a.ndim)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60]
1


In [16]:
print(a[1])
print(a[-1])
print(a[5:10])
print(a[:11])
print(a[:])
print(a[::-1])


31
60
[35 36 37 38 39]
[30 31 32 33 34 35 36 37 38 39 40]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60]
[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37
 36 35 34 33 32 31 30]


In [17]:
# 2d array with3*4 order
a=np.array([[64,85,77,45],
            [56,79,81,5],
            [7,12,5,88]])
print(a[:2,:3])

[[64 85 77]
 [56 79 81]]


In [18]:
print(a[:3,1:4])

[[85 77 45]
 [79 81  5]
 [12  5 88]]


In [21]:
a=np.arange(24)
b=np.reshape(a,(2,3,4))
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
a=np.arange(6)
b=np.reshape(a,(6))
print(b)

[0 1 2 3 4 5]


In [22]:
print(b[0,:2,1:4])

[[1 2 3]
 [5 6 7]]


In [23]:
print(b[1,:2,1:4])

[[13 14 15]
 [17 18 19]]


shape manipulation

In [2]:
# reshape
a=np.array([[5,5,4,7,8,8,5,7,8,5,8,8,5,8,8,8]])
print(a.shape)
print(a.ndim)

(1, 16)
2


In [3]:
a=np.array([[5,5,4,7,8,8,5,7,8,5,8,8,5,8,8,8]])
print(a.shape)
b=np.reshape(a,(4,4))
print(b)
print(b.shape)

(1, 16)
[[5 5 4 7]
 [8 8 5 7]
 [8 5 8 8]
 [5 8 8 8]]
(4, 4)


In [4]:
a=np.array([[5,5,4,7,8,8,5,7,8,5,8,8,5,8,8,8]])
b=np.reshape(a,(2,8))
print(b)
print(b.shape)

[[5 5 4 7 8 8 5 7]
 [8 5 8 8 5 8 8 8]]
(2, 8)


In [39]:
a=np.array([[5,5,4,7,8,8,5,7,8,5,8,8,5,8,8,8]])
b=np.reshape(a,(8,2))
print(b)
print(b.shape)

[[5 5]
 [4 7]
 [8 8]
 [5 7]
 [8 5]
 [8 8]
 [5 8]
 [8 8]]
(8, 2)


In [ ]:
#--flattening-- ==>converts 2d/3d into =1d
a=np.array([[5,5,4],
            [7,8,8],
            [5,7,8],
            [5,8,8]])
b=a.flatten()
print(b)

[5 5 4 7 8 8 5 7 8 5 8 8]


In [41]:
a=np.array([[[5,5,4],
            [7,8,8],
            [5,7,8],
            [5,8,8]]])
b=a.flatten()
print(b)

[5 5 4 7 8 8 5 7 8 5 8 8]


In [ ]:
# --2d array with 4*3--1d--in 2 ways
a=np.array([[5,4,4],
            [7,8,8],
            [5,7,8],
            [5,8,8]])
b=a.flatten()
print(b)
c=np.reshape(a,(12,))
print(c)

[5 4 4 7 8 8 5 7 8 5 8 8]
[5 4 4 7 8 8 5 7 8 5 8 8]


In [47]:
# --transpose-- swape rows and columns
a=np.array([[5,5,4],
            [7,8,8],
            [5,7,8],
            [5,8,8]])
b=np.transpose(a)
print(b)

[[5 7 5 5]
 [5 8 7 8]
 [4 8 8 8]]


adding / removing dimensions

In [ ]:
#1) np.newaxis
a=np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [49]:
b=a[:,np.newaxis]
print(b)
print(b.ndim)

[[1]
 [2]
 [3]]
2


In [50]:
c=b[:,np.newaxis]
print(c)
print(c.ndim)

[[[1]]

 [[2]]

 [[3]]]
3


In [33]:
#2) np.expand dimensions
a=np.array([1,2,3])
print(a)
print(a.shape)
b=np.expand_dims(a,axis=0)
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)


In [34]:
c=np.expand_dims(a,axis=1)
print(c)
print(c.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [36]:
# add two dimensions
a=np.array([1,2,3])
b=np.expand_dims(np.expand_dims(a,axis=0),axis=-1 )
print(b)

[[[1]
  [2]
  [3]]]


In [40]:
a=np.array([1,2,3])
b=np.expand_dims(np.expand_dims(a,axis=0),axis=-1) 
print(b)

[[[1]
  [2]
  [3]]]


In [63]:
# 3)np.squeeze
a=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(a.ndim)
b=np.squeeze(a)
print(b)


3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
a=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(a.ndim)
b=np.squeeze(a)
print(b)

3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
a=np.array([[1,2,3]])
b=np.squeeze(a)
print(a.shape)
print(b.shape)
print(b)

(1, 3)
(3,)
[1 2 3]


In [53]:
a=np.array([[1],
            [2],
            [3]])
print(a.shape)
b=np.squeeze(a)
print(b.shape)

(3, 1)
(3,)


joining

In [64]:
# 1)np.concatenate
# 1d
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)


[1 2 3 4 5 6]


In [2]:
# 2d
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=np.concatenate(((a,b)))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# 3d
a=np.array([[[1,2],
             [3,4]]])
b=np.array([[[5,6],
             [7,8]]])
c=np.concatenate((a,b))
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# coloumn Wise
a=np.array([[[1,2],
             [3,4]]])
b=np.array([[[5,6],
             [7,8]]])
c=np.concatenate((a,b),axis=1)
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
# row Wise
a=np.array([[[1,2],
             [3,4]]])
b=np.array([[[5,6],
             [7,8]]])
c=np.concatenate((a,b),axis=2)
print(c)

[[[1 2 5 6]
  [3 4 7 8]]]


In [8]:
# stack
# 1d
a=np.array([1,2])
b=np.array([5,6])
c=np.stack((a,b),axis=0)
print(c)

[[1 2]
 [5 6]]


In [9]:
a=np.array([1,2])
b=np.array([5,6])
c=np.stack((a,b),axis=1)
print(c)

[[1 5]
 [2 6]]


In [10]:
# 2d
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.stack((a,b),axis=0)
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [11]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.stack((a,b),axis=1)
print(c)
print(c.shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [12]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.stack((a,b),axis=2)
print(c)
print(c.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [13]:
# stack
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
# hstack
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.hstack((a,b))
print(c)
print(c.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [15]:
# dstack
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
           [7,8]])
c=np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


splitting

In [16]:
# 1) np.split 
a=np.array([1,2,3,4,5,6])
b=np.split(a,2)
print(b)

[array([1, 2, 3]), array([4, 5, 6])]


In [18]:
# split array with a specific indecies
a=np.array([1,2,3,4,5,6])
b=np.split(a,[2,4])
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 2)np.hsplit 
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
b=np.hsplit(a,3)
print(b)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [ ]:
# specific index
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
b=np.hsplit(a,[2])
print(b)

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [21]:
# vsplit 
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
b=np.vsplit(a,2)
print(b)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [22]:
# specific index
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
b=np.vsplit(a,[1])
print(b)

[array([[1, 2, 3]]), array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])]


In [24]:
# dsplit
a=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]]])
b=np.dsplit(a,3)
print(b)

[array([[[ 1],
        [ 4],
        [ 7],
        [10]]]), array([[[ 2],
        [ 5],
        [ 8],
        [11]]]), array([[[ 3],
        [ 6],
        [ 9],
        [12]]])]


In [25]:
# specifc index
a=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]]])
b=np.dsplit(a,[2])
print(b)

[array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]]), array([[[ 3],
        [ 6],
        [ 9],
        [12]]])]


searching

In [28]:
# 1) np.where()
a=np.array([1,2,3,4,5,])
b=np.where(a>3,a,0)
print(b)

[0 0 0 4 5]


In [29]:
# on different arrays
x=np.array([1,2,3,4,2])
y=np.array([10,20,30,40,50])
a=np.where(x>3,x,y)
print(a)

[10 20 30  4 50]


In [30]:
# 2)np.non-zero 
a=np.array([0,1,2,0,4,9,0])
b=np.nonzero(a)
print(b)

(array([1, 2, 4, 5]),)


In [31]:
# 3)argwhere
a=np.array([0,1,2,3,0,4])
b=np.argwhere(a>2)
print(b)

[[3]
 [5]]


sorting

In [ ]:
import numpy as np

In [2]:
a=np.array([100,2,850,56])
b=np.sort(a)
print(b)

[  2  56 100 850]


In [ ]:
# 2d--row wise 
a=np.array([[21,42,3],
            [75,4,16]])
b=np.sort(a)
print(b)

[[ 3 21 42]
 [ 4 16 75]]


In [2]:
a=np.array([[21,42,3],
            [75,4,16]])
b=np.sort(a,axis=1)
print(b)

[[ 3 21 42]
 [ 4 16 75]]


In [3]:
# 2d--column wise 
a=np.array([[21,42,3],
            [75,4,16]])
b=np.sort(a,axis=0)
print(b)

[[21  4  3]
 [75 42 16]]


In [5]:
# sort() des--asc 
a=np.array([[21,42,3]])
b=-np.sort(-a)
print(b)

[[42 21  3]]


In [7]:
# 2d column sort dec oreder
a=np.array([[21,42,3],
            [75,4,16]])
b=-np.sort(-a,axis=1)
print(b) 


[[42 21  3]
 [75 16  4]]


In [9]:
a=np.array([100,2,850,56,25])
b=np.argsort(a)
print(b)
c=np.sort(a)
print(c)

[1 4 3 0 2]
[  2  25  56 100 850]


In [10]:
a=np.array([100,2,850,56,25])
b=np.argsort(-a)
print(b)

[2 0 3 4 1]


Broadcating

In [11]:

# 1d
a=np.array([1,2,3])
b=5
c=a+b
print(c)

[6 7 8]


In [12]:
# 2d
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([10,20,30])
c=a+b
print(c)

[[11 22 33]
 [14 25 36]]


Masking

In [20]:
# 1d
a=np.array([1,2,3,4,5])
mask=a
print(mask)

[1 2 3 4 5]


In [23]:
# select element from an array
c=a[mask]
print(c)

[4 5 6]


In [22]:
a=np.array([[1,2,3],
            [4,5,6]])
mask=a>3
print(mask)
c=a[mask]
print(c)

[[False False False]
 [ True  True  True]]
[4 5 6]
